import hexaPawn
board=hexaPawn.Board()
board.setStartingPosition()
print(board.getPosition())
print(board.generateMoves(),board.turn)
board.applyMove((8,5))
print(board.getPosition())
print(board.generateMoves(),board.turn)
board.applyMove((1,5))
print(board.getPosition())
print(board.generateMoves(),board.turn)
board.applyMove((7,4))
print(board.getPosition())
print(board.generateMoves(),board.turn)
board.applyMove((5,8))
print(board.getPosition())
print(board.generateMoves(),board.turn)
print(board.isTerminal())